name: Publish
on:
  push:
    branches: [ master ]   
  workflow_dispatch:  
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    env:
      config: 'Release'
      framework: 'net8.0-browserwasm'
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore Dependencies
      run: dotnet restore ./BFInterpreter/BFInterpreter.csproj
    - name: Build 
      run: dotnet build ./BFInterpreter/BFInterpreter.csproj --no-restore -f $framework -c $config -p:WasmShellWebAppBasePath=./

    - name: Add COOP and COEP
      run: curl -o ./BFInterpreter/bin/${{env.config}}/${{env.framework}}/dist/coi-serviceworker.js https://raw.githubusercontent.com/gzuidhof/coi-serviceworker/master/coi-serviceworker.js && sed -i '/<\/head>/ i <script src="coi-serviceworker.js"></script>' ./BFInterpreter/bin/${{env.config}}/${{env.framework}}/dist/index.html
    - name: Publish Artifacts
      uses: actions/upload-artifact@v4
      if: github.event_name == 'workflow_dispatch' # Only deploy if Workflow manually ran
      with:
        name: pages
        path: ./BFInterpreter/bin/${{env.config}}/${{env.framework}}/dist/        
  deploy:
    needs: build 
    runs-on: ubuntu-latest
    name: Deploy
    if: github.event_name == 'workflow_dispatch' # Only deploy if Workflow manually ran
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: pages
        path: dist        
    - name: Deploy to GitHub Pages
      uses: crazy-max/ghaction-github-pages@v4
      with:
        target_branch: gh-pages
        build_dir: ./dist/
        jekyll: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
